const actionTypes = {
  SHOW_MESSAGE: "SHOW_MESSAGE",
  HIDE_MESSAGE: "HIDE_MESSAGE",
  REQUEST_PROCESSING: "REQUEST_PROCESSING",
  SIGNIN_SUCCESSFUL: "SIGN_SUCCESSFUL",
  SIGNIN_UNSUCCESSFUL: "SIGN_UNSUCCESSFUL",
  SET_CURRENT_USER: "SET_CURRENT_USER",
  LOGOUT_CURRENT_USER: "LOGOUT_CURRENT_USER",
  FETCH_STATES: "FETCH_STATES",
  SHOW_PROCESSING_MODAL: "SHOW_PROCESSING_MODAL",
  CLOSE_PROCESSING_MODAL: "CLOSE_PROCESSING_MODAL",
  SERVER_ERROR: "SERVER_ERROR",
  SHOW_MODAL: "SHOW_MODAL",
  CLOSE_MODAL: "CLOSE_MODAL",
  START_DETAILS_VIEW: "START_DETAILS_VIEW",
  STOP_DETAILS_VIEW: "STOP_DETAILS_VIEW",
  IS_SUCCESSFUL: "IS_SUCCESSFUL",
  UPDATE_USER: "UPDATE_USER",
  IS_FETCHING: "IS_FETCHING",
  SET_STATIC_MODAL: "SET_STATIC_MODAL"
};

export default actionTypes;
