const SHOW_MESSAGE = "SHOW_MESSAGE";
const HIDE_MESSAGE = "HIDE_MESSAGE";
const REQUEST_PROCESSING = "REQUEST_PROCESSING";
const SIGNIN_SUCCESSFUL = "SIGN_SUCCESSFUL";
const SIGNIN_UNSUCCESSFUL = "SIGN_UNSUCCESSFUL";
const SET_CURRENT_USER = "SET_CURRENT_USER";
const LOGOUT_CURRENT_USER = "LOGOUT_CURRENT_USER";
const FETCH_STATES = "FETCH_STATES";

const actionTypes = {
  SHOW_MESSAGE,
  HIDE_MESSAGE,
  REQUEST_PROCESSING,
  SIGNIN_SUCCESSFUL,
  SIGNIN_UNSUCCESSFUL,
  SET_CURRENT_USER,
  LOGOUT_CURRENT_USER,
  FETCH_STATES
};

export default actionTypes;
