const SHOW_MESSAGE = "SHOW_MESSAGE";
const HIDE_MESSAGE = "HIDE_MESSAGE";
const REQUEST_PROCESSING = "REQUEST_PROCESSING";
const SIGNIN_SUCCESSFUL = "SIGN_SUCCESSFUL";
const SIGNIN_UNSUCCESSFUL = "SIGN_UNSUCCESSFUL";
const SET_CURRENT_USER = "SET_CURRENT_USER";
const LOGOUT_CURRENT_USER = "LOGOUT_CURRENT_USER";
const FETCH_STATES = "FETCH_STATES";
const SHOW_PROCESSING_MODAL = "SHOW_PROCESSING_MODAL";
const CLOSE_PROCESSING_MODAL = "CLOSE_PROCESSING_MODAL";
const SERVER_ERROR = "SERVER_ERROR";
const SHOW_MODAL = "SHOW_MODAL";
const CLOSE_MODAL = "CLOSE_MODAL";

const actionTypes = {
  SHOW_MESSAGE,
  HIDE_MESSAGE,
  REQUEST_PROCESSING,
  SIGNIN_SUCCESSFUL,
  SIGNIN_UNSUCCESSFUL,
  SET_CURRENT_USER,
  LOGOUT_CURRENT_USER,
  FETCH_STATES,
  SHOW_PROCESSING_MODAL,
  CLOSE_PROCESSING_MODAL,
  SERVER_ERROR,
  SHOW_MODAL,
  CLOSE_MODAL
};

export default actionTypes;
